[tools]
node = "20"
ruby = "3.4"
"gem:rubocop" = "latest"
"gem:ruby-lsp" = "latest"
"gem:erb-formatter" = "latest"
"npm:prettier" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
